export const ADD_MATERIAL = "ADD_MATERIAL";
export const UPDATE_COMPARED = "UPDATE_COMPARED";
export const REMOVE_MATERIAL = "REMOVE_MATERIAL";
export const SET_ROTATION = "SET_ROTATION";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
