export const ADD_MATERIAL = "ADD_MATERIAL";
export const UPDATE_COMPARED = "UPDATE_COMPARED";
export const REMOVE_MATRIX = "REMOVE_MATRIX";
export const SET_ROTATED = "SET_ROTATED";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const ROTATE_MATRIX = "ROTATE_MATRIX";
export const RESET_MATRIX = "RESET_MATRIX";
