export const CELL_CHANGED = 'CELL_CHANGED';
export const CRYSTAL_SYSTEM_CHANGED = 'CRYSTAL_SYSTEM';
export const MATERIAL_KEYWORD_CHANGED = 'MATERIAL_KEYWORD_CHANGED';
export const UPDATE_TO_SEARCH_RESULT = 'UPDATE_TO_SEARCH_RESULT';
export const SUBMIT_PHASE = 'SUBMIT_PHASE';
export const PROCESS_POINTS = 'PROCESS_POINTS';
export const PROCESS_TABLES = 'PROCESS_TABLES';