export const CELL_CHANGED = 'CELL_CHANGED';
export const CRYSTAL_SYSTEM_CHANGED = 'CRYSTAL_SYSTEM';
export const MATERIAL_KEYWORD_CHANGED = 'MATERIAL_KEYWORD_CHANGED';
export const UPDATE_TO_SEARCH_RESULT = 'UPDATE_TO_SEARCH_RESULT';
export const SUBMIT_PHASE = 'SUBMIT_PHASE';
export const PROCESS_POINTS = 'PROCESS_POINTS';
export const PROCESS_TABLES = 'PROCESS_TABLES';
export const CHANGE_TENSOR = 'CHANGE_TENSOR';
export const ELASTICITY_FROM_SEARCH = 'ELASTICITY_FROM_SEARCH';
export const PROCESS_RANGE_RUN_POINTS = 'PROCESS_RANGE_RUN_POINTS';
export const PROCESS_WORKERS_MESSAGE = 'PROCESS_WORKERS_MESSAGE';

